

module AbsIntExp where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq,Ord,Show,Read)
data IntExp =
   EAdd IntExp IntExp
 | EMin IntExp
 | EMul IntExp IntExp
 | Eint Integer
 | Evar Ident
  deriving (Eq,Ord,Show,Read)

