module SkelIntExp where

-- Haskell module generated by the BNF converter

import AbsIntExp
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident str  -> failure x


transIntExp :: IntExp -> Result
transIntExp x = case x of
  EAdd intexp1 intexp2  -> failure x
  EMin intexp  -> failure x
  EMul intexp1 intexp2  -> failure x
  Eint n  -> failure x
  Evar id  -> failure x



